# Generated by Django 2.2.4 on 2019-10-11 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20191011_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlepost',
            old_name='update_time',
            new_name='updated_time',
        ),
    ]
